### PR TITLE
Support chart in windows

### PR DESCRIPTION
**Pull request by saroad2**
I refactored the `draw_text` function so rendering charts would work in Windows. This is how it looks:
chart

The problem is that this doesn't affect well on Mac:
bug

I think that the reason for that is a bug in `Canvas.reset_transform` in  *toga_cocoa*. would you mind checking it?

### CODE REVIEW

**Comment by freakboy3742** [comment]
I resolved the issue with Cocoa as well - see beeware/toga#920.

**Comment by saroad2** [comment]
The reason that the y-axis title is missing is that it is rendered outside the Canvas. When I added te following line to the code:
```python
        if ismath:
            path, transform = self._get_text_path_transform(x, y, s, prop, angle, ismath)
            color = gc.get_rgb()

            gc.set_linewidth(.75)
            self.draw_path(gc, path, transform, rgbFace=color)
        else:
            print("text=", s, "x=", x, "y=", y)  # ADDED THIS PRINT
            self._renderer.translate(x, y)
            self._renderer.rotate(-math.radians(angle))
            with self._renderer.fill(color=self.to_toga_color(*gc.get_rgb())) as fill:
                font = self.get_font(prop)
                fill.write_text(s, x=0, y=0, font=font)
            self._renderer.reset_transform()
```

I got this printing:
```
text= Probability density x= -2.7777777777777803 y= 274.5
text= Histogram: \mu=100, \sigma=15 x= 88.75 y= 39.666666666666686
```

You can see that the y-axis title has a negative x-coordinate. I don't know why, but it seems like a bug in *Matplotlib*.

**Comment by freakboy3742** [comment]
I don't think it's a matplotlib error - or if it is, it's not a simple problem. On Cocoa, those two lines line output:
```
text= Probability density x= 18.19780815972222 y= 244.076171875
text= Histogram: $\mu=100$, $\sigma=15$ x= 156.0283203125 y= 39.666666666666686
```
That's why I suspect it's related to the fonts - the sizes that are being rendered are larger than their Cocoa and GTK equivalent; which, if the positioning of the *chart* is fixed, the larger fonts might lead to offsets that push the x-coordinate negative.

**Comment by saroad2** [comment]
You are right! The problem was that `font.measure` returns the size in **pixels** while *Matplotlib* (and I guess *Toga* too) expects the units in **points**.
Therefore the sizes were a lot bigger!

The question is: in which units we we the width and height units be in *Toga* by default?

**Comment by saroad2** [comment]
I think beeware/toga#710 would fix the problem, but would need to check after the PR will be merged

**Comment by freakboy3742** [comment]
Hrm - I'm not sure beeware/toga#919 will fix this completely - none of the changes I made altered font measurement. I'll test that as part of the work I'm doing on that PR.

**Comment by freakboy3742** [comment]
I think I've now resolved the issues related to DPI sizing - and for a treat, I've thrown in antialiasing as well. When combined with beeware/toga#919, you now get:

image

I've tested this at 150% scaling, and it renders exactly the same; I've also tested Cocoa and Linux.

@saroad2 If you can confirm this all works for you, I'll merge this PR and the Toga one.

**Comment by saroad2** [comment]
Hi friend! I cannot validate it because I don't have access to your PR branch in *Toga*.
If you merge the *Toga* PR I could check this using `pip install -e toga`.

**Comment by freakboy3742** [comment]
Ok: so we probably need to document this better, but if you've got a Toga checkout, you can run:
```
pip install -e src/core
pip install -e src/winforms
```
to use your Git checkout as the installed version for testing.

If you're using briefcase, you can use the same two paths (with whatever `../` prefixing is appropriate) in your `requires` lists for pyproject.toml (with `core` being a global requires, and `winforms` being a windows-specific requires)

**Comment by freakboy3742** [comment]
You can also check out any branch; the easiest way to do this is to get the [github command line tool](https://cli.github.com/) - once that's installed, it's a matter of
```
$ gh pr checkout 919
```
to get a checkout of PR 919 (relative to whatever repo you're in)

**Pull request merged**
